### ISSUE TITLE
[Đào tạo] Sửa import Giảng viên

### ISSUE THREAD

**Issue by phongtt35** [FPLHN-FACTORY/fplhn-capstone-register#10]
- Không cần tên cơ sở, tự động lấy theo cơ sở của người đang đăng nhập
- Không cần lấy tên đợt đăng ký, tự động lấy theo đợt hiện tại
- Bổ sung môn học mà Giảng viên có thể hướng dẫn

**Comment by vinhnv01** [comment]
vâng thầy
