### ISSUE TITLE
[Đào tạo] Không import được Cán bộ

### ISSUE THREAD

**Issue by phongtt35** [FPLHN-FACTORY/fplhn-capstone-register#11]
![image](https://user-images.githubusercontent.com/77969224/201180823-a9d37c2c-a6c4-4ba9-bdac-6baae2905aca.png)

**Comment by nguyendinhcao2k2** [comment]
Thầy ơi số điện thoại phải 11 số mới import đc

**Comment by phongtt35** [comment]
> Thầy ơi số điện thoại phải 11 số mới import đc

ối giồi ôi, sửa ngay

**Comment by nguyendinhcao2k2** [comment]
Bao nhiêu số cx import đc hả thầy

**Comment by phongtt35** [comment]
> Thầy ơi số điện thoại phải 11 số mới import đc

vẫn không được nhé, bạn cho mình dữ liệu chạy được đi

**Comment by nguyendinhcao2k2** [comment]
Em gửi thầy file excel zalo ý thầy thử import file ý xem đc k ạ

**Comment by phongtt35** [comment]
> Em gửi thầy file excel zalo ý thầy thử import file ý xem đc k ạ

bạn gửi mình file bạn chạy được đi

**Comment by sonpt199** [comment]
Đã xong
