### ISSUE TITLE
[FrontEnd] Fix button Thêm, bỏ toggle-modal và sử dụng onclick và function - Sửa lỗi bấm thêm bị chết màn

### ISSUE THREAD

**Issue by sonpt199** [FPLHN-FACTORY/fplhn-capstone-register#21]
Gấp, sửa
![hình ảnh_2022-11-13_025010639](https://user-images.githubusercontent.com/101123609/201492031-fa55784e-50b2-4d63-9bf3-986bea5e9c7c.png)
![image](https://user-images.githubusercontent.com/101123609/201492044-c8715627-a179-4be2-a053-21a556b88ae4.png)

**Comment by xuanhai2907** [comment]
Đã sửa

**Comment by thangdtph27626** [comment]
Đã sửa
