### ISSUE TITLE
[FrontEnd] Nút x và nút hủy không tắt được modal

### ISSUE THREAD

**Issue by sonpt199** [FPLHN-FACTORY/fplhn-capstone-register#22]
Tất cả các nút x và nút hủy ở modal mọi người sửa data-dismiss="modal" thành data-bs-dismiss="modal"
![image](https://user-images.githubusercontent.com/101123609/201493053-23bd7abe-ff0a-457f-bf6f-543881628883.png)

**Comment by xuanhai2907** [comment]
Đã sửa

**Comment by thangdtph27626** [comment]
Đã sửa
